### ISSUE TITLE
Any idea if this will be integrated in the quasar cli?

### ISSUE THREAD

**Issue by paulvanbladel** [JDrechsler/Quasar-with-TS-using-vue-cli-3#2]
Very nice. Thanks for sharing.
Any idea if this will be integrated in the quasar cli?

**Comment by JDrechsler** [comment]
Hi, I am sorry that I just saw that issue. This April I talked to rstoenescu about it on discord and he said it is planned. I can't really say much more.

**Comment by paulvanbladel** [comment]
No worries.
Nice to hear it's on the planning.
Cheers.
